import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Brain, MessageSquare, Target, Zap } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="min-h-screen gradient-bg">
      <div className="container mx-auto px-4 py-16">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-6xl font-bold mb-6 gradient-text">
            AI Interview Genius
          </h1>
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Master your next interview with AI-powered practice sessions tailored to your role and skills
          </p>
          <Link href="/interview">
            <Button size="lg" className="text-lg px-8 py-6">
              Start Interview Practice
              <Zap className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>

        {/* Features */}
        <div className="grid md:grid-cols-3 gap-8 mb-16">
          <Card className="card-hover">
            <CardHeader>
              <Brain className="h-12 w-12 text-primary mb-4" />
              <CardTitle>AI-Powered Questions</CardTitle>
              <CardDescription>
                Get personalized interview questions generated by advanced AI based on your target role
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="card-hover">
            <CardHeader>
              <MessageSquare className="h-12 w-12 text-primary mb-4" />
              <CardTitle>Real-time Feedback</CardTitle>
              <CardDescription>
                Receive instant, detailed feedback on your responses to improve your interview skills
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="card-hover">
            <CardHeader>
              <Target className="h-12 w-12 text-primary mb-4" />
              <CardTitle>Role-Specific Practice</CardTitle>
              <CardDescription>
                Practice with questions tailored to specific job categories and technical skills
              </CardDescription>
            </CardHeader>
          </Card>
        </div>

        {/* CTA Section */}
        <div className="text-center">
          <Card className="max-w-2xl mx-auto">
            <CardContent className="pt-6">
              <h2 className="text-2xl font-bold mb-4">Ready to ace your next interview?</h2>
              <p className="text-muted-foreground mb-6">
                Join thousands of professionals who have improved their interview skills with our AI-powered platform
              </p>
              <Link href="/interview">
                <Button size="lg">
                  Get Started Now
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}